### PR TITLE
Do not overwrite outDir/outFile already defined in tsconfig.json

### PR DESCRIPTION
**Pull request by hippich**

### CODE REVIEW

**Comment by pocesar** [comment]
thanks for the PR. the problem I see (I tried in a project of mine) is that a merge from other projects that set their own outDir / outFile for their use case, and not mine (thus the overrides using Grunt), gets placed in the wrong place instead of my intended mapping in Grunt. 
what is the problem you're facing?

**Comment by hippich** [comment]
In my particular case I am trying to use grunt-newer plugin. But since i need compiled files to be outted into folder, i have to set "dest" to a folder. and grunt-newer fails in such scenario. If I do not set 'dest' for typescript_project (and leave only "src"), typescript_project comes up with "dest" folder name "underfined", which is obviously is wrong place to put files to :)

So my change would allow you to override whatever "dest" is set in files configuration by setting outDir directly in tsconfig.json OR in options: { compilerOptions: { outDir: '...' } }.

And overriding outDir in `options: { compilerOptions: { outDir: '...' } }` is actually how I was able to override outDir value from tsconfig.json file.. 

Hope this makes sense.. If no - please let me know :)

**Comment by pocesar** [comment]
it does, thanks!

**Comment by hippich** [comment]
Thanks for quick response! (and great module!)

**Pull request merged**
